RedPRL/redtt

NOTICE
Maybe it is time to discuss the capitalization of `redtt`.
=> Add the NOTICE file.

src/core/Quote.ml, src/core/Tm.ml, src/core/Tm.mli, src/core/Typing.ml, src/core/Val.ml, src/frontend/ESig.ml, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Lex.mll, src/frontend/Refiner.ml, src/frontend/Refiner.mli
~@jonsterling I will keep debugging it, but if you find it please don't hesitate to commit the patch!~
By meta-meditation the God of Syntax pointed out my mistake.
=> Refine nats

src/basis/ReaderMonad.ml, src/basis/ReaderMonad.mli, src/basis/StateMonad.ml, src/basis/StateMonad.mli, src/core/Tm.ml, src/core/Tm.mli, src/frontend/Dev.ml, src/frontend/Elaborator.ml, src/frontend/Refiner.ml, src/frontend/Unify.ml
=> Immortal traversal

Makefile, equivalence.red, isotoequiv.red, src/core/IAbs.ml, src/core/Quote.ml, src/core/Tm.ml, src/core/Tm.mli, src/core/Typing.ml, src/core/Val.ml, src/core/Val.mli, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Refiner.ml, src/frontend/Unify.ml
Much nicer than both RedPRL and yacctt proof...
~By the way, there is still something getting reversed in extension type application (see #166); you can see it if you replace the nested line types here with 2-ary extension types. So annoying... Maybe someone who has a better sense of direction than I do could have a look.~
=> prove iso-to-equiv

integer.red
=> succ is an equivalence.

Makefile, omega1s1.red, src/core/Cx.ml, src/core/Domain.ml, src/core/Domain.mli, src/core/I.ml, src/core/Tm.ml, src/core/Typing.ml, src/core/Val.ml, src/frontend/Refiner.ml, src/frontend/Unify.ml
it seemed like I needed this before, but now I don't.
=> simplify domain and fix bugs

src/core/Domain.ml, src/core/DomainData.ml, src/core/Quote.ml, src/core/Val.ml
=> Add all neutral hcoms.

src/core/Domain.ml, src/core/Val.ml, src/frontend/Refiner.ml
The main change is to remove the incorrect use of unification that broke @ecavallo's code in #215; the correct code was much simpler, LOL. Thanks to @jozefg for his help in getting down with this issue.
This PR also includes random cleanup and refactoring.
Resolves #215
=> cleanup, fixes; close #215

example/retract.red, example/univalence.red
To resolve #249. I don't know what efficiency improvements are possible...
=> prove UA (IdEquiv A) is constant A

src/core/IAbs.ml
need to freshen when *unbinding*, not just binding! LOL.
=> Fix conceptual error in abstraction

src/core/Domain.ml, src/core/Domain.mli, src/core/DomainData.ml, src/core/Quote.ml, src/core/Val.ml
Gets rid of bad hack in `NCoeAtType`.
=> Immortal neutral

src/core/Domain.ml, src/core/Domain.mli, src/core/DomainData.ml, src/core/Quote.ml, src/core/Tm.ml, src/core/Tm.mli, src/core/TmData.ml, src/core/Typing.ml, src/core/Typing.mli, src/core/Val.ml, src/core/ValSig.ml, src/frontend/Contextual.ml, src/frontend/Contextual.mli, src/frontend/Dev.ml, src/frontend/Dev.mli, src/frontend/ElabMonad.ml, src/frontend/Elaborator.ml, src/frontend/Refiner.ml, src/frontend/Unify.ml
@mortberg @cangiuli 
Also resolves #244 and #231
=> use closures for extension type lambdas; replace Tm.Rst with Tm.Ext; renaming

example/equivalence.red, src/core/Val.ml
=> fix right face of vproj

src/basis/Bwd.ml, src/basis/Bwd.mli, src/core/Cx.ml, src/core/Domain.ml, src/core/Domain.mli, src/core/DomainData.ml, src/core/GlobalEnv.ml, src/core/GlobalEnv.mli, src/core/Quote.ml, src/core/Typing.ml, src/core/Val.ml, src/core/ValSig.ml, src/frontend/Elaborator.ml, src/frontend/Refiner.ml
(Don't get your hopes up, this doesn't fix the bug we were trying to fix .but it's clearly wrong!)
=> fix a bug in coe of extension type; various other cleanup

example/connection.red
=> Remove duplicate code.

example/Makefile, example/equivalence.red, example/hedberg.red, example/int.red, example/invariance.red, example/isotoequiv.red, example/modal.red, example/nat.red, example/ntype.red, example/omega1s1.red, example/or.red, example/path.red, example/pointed.red, example/retract.red, example/s1.red, example/torus.red, example/unit.red, example/univalence.red, src/basis/ListUtil.ml, src/core/Tm.ml, src/frontend/Grammar.mly, vim/syntax/redtt.vim
Really wanted to change `ESig` but I can still project my thought.
@jonsterling I noticed that many files under `examples` are missing in the `Makefile` and thus not checked. Should we just check everything under `examples`?
=> An attempt to have a better grammar. Close #158.

example/pointed.red, example/problem.red, example/s3-to-join.red
From https://github.com/mortberg/cubicaltt/blob/pi4s3/examples/problem.ctt.
redtt gets stuck on `innerpath`. @mortberg
=> Port problem.ctt

example/equivalence.red, example/omega1s1.red, example/univalence.red, src/core/Domain.ml, src/core/DomainData.ml, src/core/Quote.ml, src/core/Tm.ml, src/core/TmData.ml, src/core/Typing.ml, src/core/Val.ml, src/core/ValSig.ml, src/frontend/Grammar.mly
Now, `vproj` needs only the data that appears in Part III. Yay!
=> Simplify vproj

example/s3-to-join.red
We are killing dead faces now.
=> Tweak s3-join-s3.

example/omega1s2.red, src/core/Val.ml
This is not related to the Brunerie number, but it's a pet theorem I've tried to formalize a few times over the years. I got it from a [blog post of Egbert's](https://egbertrijke.com/2016/09/28/the-loop-space-of-the-2-sphere/), and I believe it's an instance of a more general theorem in his thesis (?).
The file takes a little under a minute to check on my machine. I've replaced the current `coe` in datatypes with the identity function in this branch, which is valid for datatypes without parameters. Without that change, it seems to get intractable around `s2/encode-decode/base/step`.
First `redtt`-exclusive formalized result (as far as I know) 🎉
=> Loop space of S2

Makefile, README.md, example/J.red, example/connection.red, example/hedberg.red, example/omega1s1.red, example/omega1s2.red, example/path.red, example/pointed.red, example/retract.red, example/s1.red, example/s2.red, example/s3-to-join.red, example/torus.red, src/frontend/Grammar.mly, src/frontend/Lex.mll, vim/syntax/redtt.vim
While we're golfing code, what do folks think about this notation?
/cc @mortberg @cangiuli @ecavallo @favonia
=> add notation for boundary of a set of dimensions??

example/J.red, example/bool.red, example/connection.red, example/equivalence.red, example/hedberg.red, example/int.red, example/invariance.red, example/isotoequiv.red, example/modal.red, example/nat.red, example/ntype.red, example/omega1s1.red, example/omega1s2.red, example/or.red, example/path.red, example/pointed.red, example/problem.red, example/retract.red, example/s1.red, example/s2.red, example/s3-to-join.red, example/torus.red, example/unit.red, example/univalence.red, example/void.red, src/frontend/Lex.mll, src/frontend/Refiner.ml, vim/syntax/redtt.vim
Comments and suggestions welcome
=> first cut at imposing some lexical conventions; new comment style

example/bool.red, example/int.red, example/invariance.red, example/isotoequiv.red, example/moebius-boundary.red, example/nat.red, example/omega1s1.red, example/omega1s2.red, example/or.red, example/pointed.red, example/s1.red, example/s2.red, example/s3-to-join.red, example/torus.red, example/unit.red, example/void.red, src/basis/ListUtil.ml, src/frontend/ESig.ml, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Lex.mll, src/frontend/Refiner.ml, src/frontend/Refiner.mli
This is a nice tactic. For instance, consider the following code from `torus.red`:
```
let c2t2c/transpose : (c0 c1 : s1) → path (s1 × s1) (t2c (c2t/transpose c0 c1)) (c0, c1) =
λ [ _ → λ [ _ → refl ] ]
```
The declaration of `c2t2c/transpose` gets elaborated to the following monster:
```
(λ [x]
(s1.elim
[x1] (→ [c1 : s1]
(# <i>
(× [x1 : s1] s1)
[i=0
(torus.elim
[x1] (× [x1 : s1] s1)
((s1.elim
[x1] (→ [x1 : s1] torus)
x1
(base (λ [x1] (s1.elim [x1] torus x1 (base pt) (loop [x1] (p/two x1)))))
(loop
[x1]
(λ [x1]
(s1.elim [x1] torus x1 (base (p/one x1)) (loop [x1] (square x1 x1))))))
c1)
(pt (pair base base))
(p/one [x1] (pair (loop x1) base))
(p/two [x1] (pair base (loop x1)))
(square [x1 x1] (pair (loop x1) (loop x1))))]
[i=1 (pair x1 c1)]))
x
(loop
[i]
(λ [x1]
(s1.elim
[x1] (# <i1>
(× …
```
=> add support for wildcard, inversion tacticals

src/core/Typing.ml, src/core/Val.ml
The most relaxed local validity---non-bipartiteness. (See #330 for the non-local validity.)
=> More optimization with relaxed validity

src/core/Typing.ml
=> Revert one validity relaxation.

src/basis/ListUtil.ml, src/core/Quote.ml, src/core/ValSig.ml
=> Implement the eta rule of the fhcom types.

src/core/Typing.ml
Hopefully, the rewritten code is easier to read. Close #348.
=> Rewrite bipartiteness checking and fix bugs in scope checking.

example/free-monoid.red, example/join.red, example/list.red, example/or.red, example/susp.red, example/truncation.red, src/frontend/Grammar.mly, src/frontend/Lex.mll, vim/ftplugin/redtt.vim
resolves #368
had to compromise a little bit to avoid grammar conflicts
=> less confusing notation for datatype parameters

vim/README.md, vim/ftplugin/redtt.vim
Write a tiny installation script, and improve vim mode's documentation while I'm at it. If we like this, I'll update the RedPRL mode similarly.
=> Close #370.

src/core/Quote.ml, src/core/Typing.ml, src/core/Val.ml, src/core/ValSig.ml
I noticed this while working on #270
=> simplify make_intro

src/core/Val.ml
I noticed this bug while working on #270.
=> fix a bug in multi-coe

src/core/Domain.ml
Little mistake when implementing parametric HITs :laughing:
=> resolve #386

library/README.md, library/retract.red, library/univalence.red
=> don't use is-* for non-prop

src/core/Quote.ml
Eta-long? Who cares? :rofl: Maybe this will work?
=> Who cares about being eta-long?

src/bin/dune
Thanks to @UlrikBuchholtz for diagnosing this issue!
=> disable profiling so that macOS Mojave users can build (close #387)

library/prelude/univalence.red
=> simplify univalence proof

src/frontend/Contextual.ml
I know it's trivial but I noticed it when messing around.
=> tiny tweak to fix a grammar error in error message

src/frontend/Contextual.ml, src/frontend/Contextual.mli, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/ResEnv.ml, src/frontend/ResEnv.mli, src/frontend/RotIO.ml, src/frontend/RotIO.mli
=> [Rot] Phase 2

src/core/Domain.ml, src/core/DomainData.ml, src/core/GlobalEnv.ml, src/core/Pp.ml, src/core/Quote.ml, src/core/Restriction.ml, src/core/Restriction.mli, src/core/Tm.ml, src/core/TmData.ml, src/core/Typing.ml, src/core/Val.ml, src/frontend/Elaborator.ml, src/frontend/Elaborator.mli, src/frontend/Grammar.mly, src/frontend/Importer.ml, src/frontend/RotIO.ml
@jonsterling I prefer to merge things more gradually...
=> Backport changes frow the new-domain PR.

library/cool/nats.red
I'm moving this out of #422. The representation is wrong, because `nil` and `cons0 nil` are both zero. Anyone (@ecavallo ?) is welcome to hack on this, but if nobody else does I'll eventually get back to it.
=> Unary and binary natural numbers.

library/cool/sphere1-to-s1.red, library/data/susp.red
Keeping up with cubical agda (https://github.com/agda/cubical/blob/master/Cubical/HITs/Susp.agda)
=> sphere1-to-s1 equivalence

src/core/Quote.ml
=> print mismatched names in Quote

src/frontend/ResEnv.ml
=> Fix Unicode printing of unresolved variables.

library/cool/hopf.red
by writing the rotate equivalence more directly. The following code now takes 2s on my machine instead of 140s:
```
def winding2 (s : [i j] s2 [∂[i j] → base]) : int =
winding (λ j → coe 0 1 base in λ i → hopf (s i j))
def test10 : int =
winding2 (λ i j → comp 0 1 (surf i j) [i=0 k → surf j k | i=1 | ∂[j] → refl])
```
=> drastically improve hopf performance

library/prelude/connection.red
changes some filler faces that were non-refl for no reason.
=> make connection/both a little better

library/cool/parametric-smash.red, library/pointed/bool.red, library/pointed/smash.red
A characterization of polymorphic maps X ∧ Y →* X ∧ Y, assuming a certain axiom that would follow from internal parametricity.
=> Parametric smash

library/cool/biinv-int.red, library/cool/s3-to-join.red, library/prelude/connection.red, library/prelude/path.red
=> Some code golfing ;)

.travis.yml, README.md, dune-project, redtt.opam
=> updating versions
