RedPRL/redtt

- redtt.vim
Here's a very rudimentary Vim syntax highlighter. It burns my eyes to read `.red` files without one.
> Vim syntax highlighting.

- connection.red
- path.red
- src/core/I.ml
- src/core/I.mli
- src/core/LocalCx.ml
- src/core/LocalCx.mli
- src/core/Quote.ml
- src/core/Tm.ml
- src/core/Typing.ml
- src/core/Val.ml
- src/core/Val.mli
- src/frontend/Dev.ml
- src/frontend/ESig.ml
- src/frontend/Elaborator.ml
- src/frontend/Grammar.mly
- src/frontend/Lex.mll
- src/frontend/Refiner.ml
- test.red
- univalence.red
This PR includes the eta law for V-types, but it also includes some a more immortal version of the elaborator that lets the user control intermediate states where boundaries don't match *yet*. But it also uncovers some bugs in other parts of the code.
> eta law for v types

- modal.red
- src/core/Cx.ml
- src/core/GlobalEnv.ml
The rule for 'open' which deleted all locks was inconsistent; a conjectured consistent version is one which doesn't delete locks past a tick.
> Fix inconsistency

- src/core/Desc.ml
- src/core/Desc.mli
- src/core/Kind.ml
- src/core/Lvl.ml
- src/core/Quote.ml
- src/core/Quote.mli
- src/core/Typing.ml
- src/frontend/Dev.ml
- src/frontend/Dev.mli
- src/frontend/ESig.ml
- src/frontend/Elaborator.ml
- src/frontend/Grammar.mly
- src/frontend/Refiner.ml
- src/frontend/Unify.ml
Resolves #203 
You can now declare a HIT with explicit level and kind, like:
```
data foo : type kan ^1 where
| con [A : type]
```
This branch also contains some renaming and general cleanup.
> HITs with declared level and kind

- example/univalence.red
To close #246.
I didn't see any obvious opportunities to improve on the yacctt algorithm. The normal form of PropIsEquivDirect is a few hundred lines shorter than that of PropIsEquiv (~750 vs ~1150).
> direct proof that IsEquiv f is a prop

- example/omega1s1-wip.red
- src/core/Typing.ml
- src/core/Val.ml
> Coersion in strict data types and Omega1(S1).

- example/omega1s1.red
- src/core/Val.ml
Resolves #253 
I think I have discovered the source of the very mysterious bug that has been owning us for two weeks, in which there was some dimension that left its scope.
My hypothesis 1.5 weeks ago was that the bug was somewhere in `coe/fhcom`, and I think it was borne out. The change I make here allows the following code to work, which used to throw an error:
```
import path
import unit
data O where
| obase @ i []
let encode_ty (p : Path unit triv triv) (i : dim) : type =
elim (p i) [ triv ⇒ O ]
let decode (o : O) : Path unit triv triv =
elim o [
| obase i ⇒ λ j →
comp 0 1 triv [
| j=0 ⇒ λ c → triv
| j=1 ⇒ λ d → triv
| i=0 ⇒ λ _ → ?
]
]
let bad-ty (o : O) (k : dim) : _ =
coe 0 1 (obase 0) in encode_ty (decode (obase k))
; this is the part that would fail before:
normalize bad-ty
``` …
> Fix bad dimension bug

- src/core/Val.ml
The `fhcom` should go from `r'` to `r`. (Until we have parameterized HITs, this is very hard to trigger.)
> fix boundary fix

- example/s3-to-join.red
The current definition of this "equivalence" is actually homotopic to a constant map. This one is less likely to be, since none of the boundary-fixing uses of `push` involve all the variables `i`,`j`,`k`. But we should really prove it is an equivalence to be sure.
@mortberg I bet this version would look real nice in cubicaltt
> fix s3-to-join, maybe

- example/problem.red
- example/s2.red
- example/univalence.red
to define the Hopf fibration without using the expensive proof that UA IdEquiv is a constant path. With `coe` in datatypes redefined as identity, `innerpath` now checks instantaneously! (Without, it takes ~2sec.)
Waiting to see if `problem` gets anywhere...
> apply Guillaume's Thought

- example/int.red
- example/omega1s2.red
- example/s1.red
- example/s2.red
- example/s3-to-join.red
- example/torus.red
- src/core/Desc.ml
- src/core/Desc.mli
- src/core/Quote.ml
- src/core/Quote.mli
- src/core/Typing.ml
- src/core/Val.ml
- src/frontend/ESig.ml
- src/frontend/Elaborator.ml
- src/frontend/Grammar.mly
- src/frontend/Refiner.ml
This is yet another intermediate stage / compromise. Now HIT constructor arguments can appear in any order, but they are processed in the rigid order (and even must appear in the rigid order in constructors and eliminators!). The next step is to process them as-written.
> working toward more flexible favonia-style HIT spec

- README.md
- vim/README.md
- vim/install.sh
The reason is, this will definitively prevent people from running this command from the wrong directory. So far everyone who has ever used the instructions (including me!) has first done so in the wrong directory, and copied a bunch of junk into their folder.
> [vim] turn the install script into a script

- src/core/Domain.ml
- src/core/DomainData.ml
- src/core/GlobalEnv.ml
- src/core/GlobalEnv.mli
- src/core/Quote.ml
- src/core/Quote.mli
- src/core/Tm.ml
- src/core/TmData.ml
- src/core/Val.ml
- src/core/ValSig.ml
- src/frontend/Contextual.ml
- src/frontend/Contextual.mli
- src/frontend/Elaborator.ml
- src/frontend/Grammar.mly
- src/frontend/ML.ml
- src/frontend/ResEnv.ml
- src/frontend/ResEnv.mli
@jonsterling I also change the name in ML from `string` to `mlval`.
> Use names instead of strings to look up a datatype.

- src/frontend/Importer.ml
- vim/README.md
- vim/ftplugin/redtt.vim
This contains three improvements to the vim mode.
- `<LocalLeader>L` and `<LocalLeader>P` add the `--ignore-cache` option.
- Typing `<LocalLeader>l` or `<LocalLeader>L` in the `redtt` output buffer will recheck the most recently checked `.red` file, if it is still open. (Requested by @jonsterling)
- When closing a `.red` buffer, only close the `redtt` output buffer if the `.red` file is the most recently checked one.
> [vim] Usability improvements.

- emacs/redtt.el
- library/basics/hedberg.red
- library/paths/equivalence.red
- src/core/Tm.ml
- src/core/Typing.ml
- src/frontend/Elaborator.ml
- src/frontend/Grammar.mly
- src/frontend/Lex.mll
- src/frontend/ML.ml
- vim/syntax/redtt.vim
> Box and cap tactics

- library/basics/hedberg.red
- library/paths/bool.red
- library/paths/hlevel.red
- library/paths/sigma.red
- library/paths/truncation.red
- src/core/Quote.ml
Since it looks like I'm stuck in #457 without a box tactic, here are some helper lemmas I've written along the way.
> Misc lemmas

- library/basics/biinv-equiv.red
- library/basics/ha-equiv.red
- library/basics/isotoequiv.red
- library/basics/retract.red
- library/cool/biinv-int.red
- library/paths/biinv-equiv.red
- library/paths/ha-equiv.red
- library/prelude/connection.red
- library/prelude/hlevel.red
- library/prelude/path.red
Right now I've proven that `int` is equivalent to `biinv-int`, which is generated by a point and a bi-invertible endomap (i.e., a map with a left and right inverse). This is easier than proving `int` is equivalent to the HIT generated by a point and a half-adjoint equivalence (the way it is typically presented), because `biinv-int` only has 0- and 1-dimensional generators.
However, I suspect it will be straightforward to show that `biinv` is equivalent to the half-adjoint version just using the standard theorems that the different definitions of equivalence are interchangeable. ETA: Maybe not.
> proofs about HIT-style integers

- library/paths/s2.red
It's not a performance win (`s2/decode` actually takes much more time to check now) but the normal forms are shorter.
> use cap tactic in paths.s2

- library/cool/biinv-int.red
@mortberg 
Turns out it is entirely possible, just requires some IH-strengthening. I did `suc`, but `pred` wouldn't be any harder.
> successor on biinv-int which cancels pred exactly

- src/core/Name.ml
OCaml's new `Pervasives` is called `Stdlib`.
> Use Stdlib instead of Pervasives.

- dune-project
- src/frontend/Grammar.mly
This is already useful now, and will be more useful in the future (Menhir's upcoming new code back-end will require `--infer`).
> Enable type inference for Menhir.
